### ISSUE TITLE
TranscEndence daxi and InfinityX armor bug

### ISSUE THREAD

**Issue by SimpRain** [Sfiguz7/TranscEndence#16]
Infinity armor overwrites and deletes daxi buff.
Tried it 3 times using daxi r (regen buff)

Situation1 wearing full infiX armor and using daxi r resulted in not getting the buff

Situation2 using the daxi r before wearing infiX armor resulted in the regen buff getting overwritten by infiX and removing infiX armor did not get the buff back

Situation3 using daxi r and putting on infiX armor EXCEPT the pants which had regen resulted in keeping the buff

From what I think, the buffs get overwritten by infiX armor and thus causing the problem

Note: riley said that "I would recomend reporting this to Transendence and telling him to re apply the affect each minute or smth, because I'm just using Slimefuns method of apply potion effects with armor."

 - Minecraft Version: 1.16.5
 - Slimefun Version: dev 878
 - Plugin Version: dev 25

**Comment by Alessio-Colombo** [comment]
As you have tested and concluded as well, this is an issue from IX, not from TE. I have run situation1 too to confirm and the Daxi buff is indeed applied, just overridden a few seconds later by IX.

I am also going to politely decline the solution proposed by Riley as it is unwise, at best.
I am NOT going to implement recurring checks and lead to an everlasting battle where our addons override each other's effects. That is NOT how it should work. Nothing will be solved by alternating between not having Daxi effects or not having IX armor effects. Not only that, having this battle ensue is only bound to bring more issues down the line.
To be precise the way I give effects wouldn't even override his, just the other way around, as you can check: give yourself some effects and then activate a Daxi, it will only override effects of the same type AND with lower amplifiers, instead of overriding them all no matter the level, and if an effect with higher amplifier is active the Daxi one only kicks in after that higher one runs out.

Since he uses Slimefun armor to apply effects, this is supposed to be reported to Slimefun. The issues Slimefun's handling of armor effects bring include overriding stronger effects when not supposed to and actually removing them entirely from the player. I am sure a quick fix will be implemented, possibly even by myself.
The way Riley handles enchantments should probably be tweaked anyway as effects are refreshed by Slimefun every 10 seconds but he applies them with a whole minute for cooldown so taking off armor ends up with still having the effects for at least another 50 and up to 60 more seconds; you may want to report this to IX as unintended.


That all being said, it may be possible (no guarantees!) for me to unilaterally prevent this from happening: this will NOT solve IX's and more in general Slimefun's armor effects issues as any other plugin applying effects will run into what described above. It should although patch the aggressive overriding meaning Daxi effects would work through Slimefun armor, /heal and whatever other feature related to potion effects could clear them (except milk as that has already been solved in the past).
Since that would just be an additional feature and is not related to this if not idirectly, as somewhat of a patch to contain overrides from other sources, I will close this issue.
For your convenience, please check any new builds to see if they tackle the topic.
