### ISSUE TITLE
The particle overloader suddenly disappeared

### ISSUE THREAD

**Issue by Sharen2020** [Sfiguz7/TranscEndence#18]
I put down the particle overloader without a problem, but when I put ordinary particles and uncharged particles into it, the particle overloader suddenly disappeared (the block disappeared). The following error reports have occurred in the background:

Error Generated: 2021-08-23-20-02

Java Environment:
  Operating System: Linux
  Java Version: 16.0.1

Server Software: Sugarcane
  Build: git-Sugarcane-1.17.1/dev-34 (MC: 1.17.1)
  Minecraft v1.17.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v4.9-canary-6ea91b1
  Caused by: TranscEndence v33 zh-CN

Installed Addons (7)
  + SlimeFunBookFix 1.4
  + InfinityExpansion 115 zh-CN
  + TranscEndence 33 zh-CN
  + FlowerPower 1.0.0
  + CMILib 1.0.3.5
  + CMI 9.0.0.9
  + Residence 5.0.0.2

Installed Plugins (53):
  + FarmControl 1.1.8
  + PluginConstructorAPI 1.0.52
  + Moeka 1.0-PublicVer
  + NoChunkLag 2.4.3
  + BlockLocker 1.10.1
  + PlaceholderAPI 2.10.10
  + UltimateAutoRestart Build 45
  + PlugMan 2.2.5
  + Boom 1.3.2
  + ConsoleSpamFix 1.8.6
  + SkinsRestorer 14.1.3
  + NoteBlockAPI 1.6.1-SNAPSHOT
  + ViaVersion 4.0.1
  + JoinMessage 1.1
  + JukeBox 1.20.6
  + LuckPerms 5.3.51
  + spark 1.5.2
  + ProtocolLib 4.7.0
  + Vault 1.7.3-b131
  + floodgate 2.0-SNAPSHOT
  + Vehicles 12.3
  + FartherViewDistance 7.0.8
  + HolographicDisplays 2.4.9
  + PlayerPoints 3.0.3
  + WorldEdit 7.2.6-beta-01+1415e6f
  + Multiverse-Core 4.3.0-b846
  + BannerMaker 2.3.1
  + HuskHomes 2.7.1
  + WorldGuard 7.0.6-beta1+0b66f3e
  + Spartan Build 423.1
  + Slimefun 4.9-canary-6ea91b1
  + DeathMessages ${project.version}
  + SlimeFunBookFix 1.4
  + CoreProtect 20.1
  + UltimateTimber 2.2.5
  + InfinityExpansion 115 zh-CN
  + TranscEndence 33 zh-CN
  + Citizens 2.0.28-SNAPSHOT (build 2359)
  + WolfyUtilities 1.7.2.0
  + SuperVanish 6.2.6
  + EliteMobs 7.3.4
  + AureliumSkills Beta 1.2.0
  + eco 6.5.0
  + FlowerPower 1.0.0
  + CitizensCMD 2.5.1
  + CustomCrafting 1.7.1.1
  + EcoEnchants 8.8.9
  + QuickShop 4.0.9.10
  + MysqlPlayerDataBridge 3.36.3
  + CMILib 1.0.3.5
  + CMI 9.0.0.9
  + CMIEInjector 1.0.2.3
  + Residence 5.0.0.2

Block Info:
  World: world_the_end
  X: 14
  Y: 62
  Z: 19
  Material: WHITE_CONCRETE
  Block Data: org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: ZOT_OVERLOADER
  Inventory: true
  Data: {"energy-charge":"2048","id":"ZOT_OVERLOADER"}

Stacktrace:

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at me.sfiguz7.transcendence.implementation.items.machines.ZotOverloader$1.tick(ZotOverloader.java:177)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:180)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:161)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1573)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:502)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1487)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1276)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Alessio-Colombo** [comment]
What is that "zn-CH"? Sounds like an unofficial version translated in some other language, which I cannot provide support for. Even if most messages can be translated, for anything Slimefun related we strongly advise against translating item names too and this is one of the cases where it breaks everything: the error happens because I am performing a check for which type the particle is (up, down, left o right) which fails because the name is not "zot right" or similar.
If you can contact whoever translated the Addon you can tell him about the above and maybe they can fix it, or revert the names for those particles; in the meantime I unfortunately have to close this - please feel free to reopen it or open a new one if anything else comes up!

**Comment by Alessio-Colombo** [comment]
A little research lead to this https://github.com/baoad/TranscEndence
Which seems to be te project you are using. I've checked it quickly and I think putting a space between the Chinese characters and the "(right)", "(left)" etc. should be enough to fix the issue, if you want to let them know. Otherwise I'm sure they can figure out how to work around it
